In [52]:
import pandas as pd

In [53]:
df = pd.read_csv("../Data/raw/nba_games_2022_2026.csv")

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9840 entries, 0 to 9839
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SEASON_ID          9840 non-null   int64
 1   TEAM_ID            9840 non-null   int64
 2   TEAM_ABBREVIATION  9840 non-null   object
 3   TEAM_NAME          9840 non-null   object
 4   GAME_ID            9840 non-null   int64
 5   GAME_DATE          9840 non-null   object
 6   MATCHUP            9840 non-null   object
 7   WL                 9840 non-null   object
 8   MIN                9840 non-null   int64
 9   FGM                9840 non-null   int64
 10  FGA                9840 non-null   int64
 11  FG_PCT             9840 non-null   float64
 12  FG3M               9840 non-null   int64
 13  FG3A               9840 non-null   int64
 14  FG3_PCT            9840 non-null   float64
 15  FTM                9840 non-null   int64
 16  FTA                9840 non-null   int64
 17  FT_PCT             9839 non-null   float64
 18  OREB               9840 non-null   int64
 19  DREB               9840 non-null   int64
 20  REB                9840 non-null   int64
 21  AST                9840 non-null   int64
 22  STL                9840 non-null   int64
 23  BLK                9840 non-null   int64
 24  TOV                9840 non-null   int64
 25  PF                 9840 non-null   int64
 26  PTS                9840 non-null   int64
 27  PLUS_MINUS         9840 non-null   int64
 28  VIDEO_AVAILABLE    9840 non-null   int64
 29  SEASON             9840 non-null   object
dtypes: float64(3), int64(21), object(6)
memory usage: 2.3+ MB

In [55]:
df.describe(include="all")

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,SEASON
count,9840.000000,9.840000e+03,9840,9840,9.840000e+03,9840,9840,9840,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9839.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.000000,9840.0,9840
unique,NaN,NaN,30,30,NaN,651,1740,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
top,NaN,NaN,BOS,Boston Celtics,NaN,2026-04-12,TOR vs. NYK,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-23
freq,NaN,NaN,328,328,NaN,30,9,4920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2460
mean,22023.500000,1.610613e+09,NaN,NaN,2.235062e+07,NaN,NaN,NaN,241.432927,41.950407,88.882825,0.472974,13.003963,35.969919,0.360734,17.677744,22.600711,0.781721,10.871240,32.844106,43.715346,26.319411,7.847256,4.877947,14.127134,19.292581,114.582520,0.000000,1.0,NaN
std,1.118091,8.655881e+00,NaN,NaN,1.118096e+05,NaN,NaN,NaN,6.433976,5.264831,7.204404,0.054669,3.954036,7.075631,0.082200,5.934503,7.078338,0.099084,3.968571,5.401615,6.736241,5.171823,3.020300,2.497370,3.971721,4.212790,12.631361,15.565382,0.0,NaN
min,22022.000000,1.610613e+09,NaN,NaN,2.220000e+07,NaN,NaN,NaN,240.000000,22.000000,64.000000,0.277000,2.000000,12.000000,0.069000,0.000000,0.000000,0.300000,0.000000,14.000000,20.000000,9.000000,0.000000,0.000000,2.000000,4.000000,66.000000,-62.000000,1.0,NaN
25%,22022.750000,1.610613e+09,NaN,NaN,2.227531e+07,NaN,NaN,NaN,240.000000,38.000000,84.000000,0.435000,10.000000,31.000000,0.306000,14.000000,18.000000,0.720000,8.000000,29.000000,39.000000,23.000000,6.000000,3.000000,11.000000,16.000000,106.000000,-10.000000,1.0,NaN
50%,22023.500000,1.610613e+09,NaN,NaN,2.235062e+07,NaN,NaN,NaN,240.000000,42.000000,89.000000,0.472000,13.000000,36.000000,0.360000,17.000000,22.000000,0.788000,11.000000,33.000000,43.000000,26.000000,8.000000,5.000000,14.000000,19.000000,114.000000,0.000000,1.0,NaN
75%,22024.250000,1.610613e+09,NaN,NaN,2.242592e+07,NaN,NaN,NaN,240.000000,45.000000,93.000000,0.511000,16.000000,41.000000,0.415000,21.000000,27.000000,0.850000,13.000000,36.000000,48.000000,30.000000,10.000000,6.000000,17.000000,22.000000,123.000000,10.000000,1.0,NaN
max,22025.000000,1.610613e+09,NaN,NaN,2.250123e+07,NaN,NaN,NaN,290.000000,65.000000,122.000000,0.689000,29.000000,65.000000,0.680000,47.000000,59.000000,1.000000,29.000000,60.000000,74.000000,50.000000,22.000000,19.000000,31.000000,37.000000,176.000000,62.000000,1.0,NaN

In [56]:
df.isna().sum()

SEASON_ID            0
TEAM_ID              0
TEAM_ABBREVIATION    0
TEAM_NAME            0
GAME_ID              0
GAME_DATE            0
MATCHUP              0
WL                   0
MIN                  0
FGM                  0
FGA                  0
FG_PCT               0
FG3M                 0
FG3A                 0
FG3_PCT              0
FTM                  0
FTA                  0
FT_PCT               1
OREB                 0
DREB                 0
REB                  0
AST                  0
STL                  0
BLK                  0
TOV                  0
PF                   0
PTS                  0
PLUS_MINUS           0
VIDEO_AVAILABLE      0
SEASON               0
dtype: int64

In [57]:
pd.set_option("display.max_columns", None)
df[df.isna().any(axis=1)]

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,SEASON
4814,22023,1610612738,BOS,Boston Celtics,22301148,2024-04-09,BOS @ MIL,L,240,37,93,0.398,17,52,0.327,0,0,NaN,12,26,38,27,11,4,12,8,91,-13,1,2023-24

In [58]:
df["GAME_ID"].value_counts().head()

GAME_ID
22200001    2
22400790    2
22400797    2
22400796    2
22400795    2
Name: count, dtype: int64

In [59]:
game_counts = df.groupby("GAME_ID").size()

game_counts.value_counts()

2    4920
Name: count, dtype: int64

In [60]:
df["is_home"] = df["MATCHUP"].str.contains("vs.", regex=False)

In [61]:
df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,SEASON,is_home
0,22022,1610612738,BOS,Boston Celtics,22200001,2022-10-18,BOS vs. PHI,W,240,46,82,0.561,12,35,0.343,22,28,0.786,6,30,36,24,8,3,11,24,126,9,1,2022-23,True
1,22022,1610612755,PHI,Philadelphia 76ers,22200001,2022-10-18,PHI @ BOS,L,240,40,80,0.500,13,34,0.382,24,28,0.857,4,27,31,16,8,3,14,25,117,-9,1,2022-23,False
2,22022,1610612744,GSW,Golden State Warriors,22200002,2022-10-18,GSW vs. LAL,W,240,45,99,0.455,16,45,0.356,17,23,0.739,11,37,48,31,11,4,18,23,123,14,1,2022-23,True
3,22022,1610612747,LAL,Los Angeles Lakers,22200002,2022-10-18,LAL @ GSW,L,240,40,94,0.426,10,40,0.250,19,25,0.760,9,39,48,23,12,4,22,18,109,-14,1,2022-23,False
4,22022,1610612753,ORL,Orlando Magic,22200003,2022-10-19,ORL @ DET,L,240,42,86,0.488,11,30,0.367,14,19,0.737,10,38,48,21,5,5,18,24,109,-4,1,2022-23,False

In [62]:
df.loc[df["GAME_ID"] == 22200003]

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,SEASON,is_home
4,22022,1610612753,ORL,Orlando Magic,22200003,2022-10-19,ORL @ DET,L,240,42,86,0.488,11,30,0.367,14,19,0.737,10,38,48,21,5,5,18,24,109,-4,1,2022-23,False
5,22022,1610612765,DET,Detroit Pistons,22200003,2022-10-19,DET vs. ORL,W,240,40,94,0.426,14,38,0.368,19,24,0.792,12,29,41,31,11,4,13,21,113,4,1,2022-23,True

In [63]:
home = df[df["is_home"]][["GAME_ID", "TEAM_ABBREVIATION", "PTS"]].rename(
    columns={"TEAM_ABBREVIATION": "home_team", "PTS": "home_points"}
)

away = df[~df["is_home"]][["GAME_ID", "TEAM_ABBREVIATION", "PTS"]].rename(
    columns={"TEAM_ABBREVIATION": "away_team", "PTS": "away_points"}
)

game_df = home.merge(away, on="GAME_ID").rename(columns={"GAME_ID": "game_id"})
game_df = game_df[["game_id", "home_team", "away_team", "home_points", "away_points"]]
game_df.head()

    game_id home_team away_team  home_points  away_points
0  22200001       BOS       PHI          126          117
1  22200002       GSW       LAL          123          109
2  22200003       DET       ORL          113          109
3  22200004       IND       WAS          107          114
4  22200005       ATL       HOU          117          107

In [64]:
home = df[df["is_home"]].copy()
away = df[~df["is_home"]].copy()

home = home.set_index("GAME_ID")
away = away.set_index("GAME_ID")

home.columns = [f"{col}_home" for col in home.columns]
away.columns = [f"{col}_away" for col in away.columns]

game_df = home.merge(away, left_index=True, right_index=True).reset_index()
game_df.head()

,GAME_ID,SEASON_ID_home,TEAM_ID_home,TEAM_ABBREVIATION_home,TEAM_NAME_home,GAME_DATE_home,MATCHUP_home,WL_home,MIN_home,FGM_home,FGA_home,FG_PCT_home,FG3M_home,FG3A_home,FG3_PCT_home,FTM_home,FTA_home,FT_PCT_home,OREB_home,DREB_home,REB_home,AST_home,STL_home,BLK_home,TOV_home,PF_home,PTS_home,PLUS_MINUS_home,VIDEO_AVAILABLE_home,SEASON_home,is_home_home,SEASON_ID_away,TEAM_ID_away,TEAM_ABBREVIATION_away,TEAM_NAME_away,GAME_DATE_away,MATCHUP_away,WL_away,MIN_away,FGM_away,FGA_away,FG_PCT_away,FG3M_away,FG3A_away,FG3_PCT_away,FTM_away,FTA_away,FT_PCT_away,OREB_away,DREB_away,REB_away,AST_away,STL_away,BLK_away,TOV_away,PF_away,PTS_away,PLUS_MINUS_away,VIDEO_AVAILABLE_away,SEASON_away,is_home_away
0,22200001,22022,1610612738,BOS,Boston Celtics,2022-10-18,BOS vs. PHI,W,240,46,82,0.561,12,35,0.343,22,28,0.786,6,30,36,24,8,3,11,24,126,9,1,2022-23,True,22022,1610612755,PHI,Philadelphia 76ers,2022-10-18,PHI @ BOS,L,240,40,80,0.500,13,34,0.382,24,28,0.857,4,27,31,16,8,3,14,25,117,-9,1,2022-23,False
1,22200002,22022,1610612744,GSW,Golden State Warriors,2022-10-18,GSW vs. LAL,W,240,45,99,0.455,16,45,0.356,17,23,0.739,11,37,48,31,11,4,18,23,123,14,1,2022-23,True,22022,1610612747,LAL,Los Angeles Lakers,2022-10-18,LAL @ GSW,L,240,40,94,0.426,10,40,0.250,19,25,0.760,9,39,48,23,12,4,22,18,109,-14,1,2022-23,False
2,22200003,22022,1610612765,DET,Detroit Pistons,2022-10-19,DET vs. ORL,W,240,40,94,0.426,14,38,0.368,19,24,0.792,12,29,41,31,11,4,13,21,113,4,1,2022-23,True,22022,1610612753,ORL,Orlando Magic,2022-10-19,ORL @ DET,L,240,42,86,0.488,11,30,0.367,14,19,0.737,10,38,48,21,5,5,18,24,109,-4,1,2022-23,False
3,22200004,22022,1610612754,IND,Indiana Pacers,2022-10-19,IND vs. WAS,L,240,39,97,0.402,15,42,0.357,14,21,0.667,12,30,42,21,7,5,15,20,107,-7,1,2022-23,True,22022,1610612764,WAS,Washington Wizards,2022-10-19,WAS @ IND,W,240,42,92,0.457,11,31,0.355,19,24,0.792,14,39,53,21,5,10,17,19,114,7,1,2022-23,False
4,22200005,22022,1610612737,ATL,Atlanta Hawks,2022-10-19,ATL vs. HOU,W,240,45,90,0.500,7,25,0.280,20,24,0.833,4,34,38,30,12,5,9,18,117,10,1,2022-23,True,22022,1610612745,HOU,Houston Rockets,2022-10-19,HOU @ ATL,L,240,42,98,0.429,9,35,0.257,14,15,0.933,15,39,54,25,4,3,16,20,107,-10,1,2022-23,False

In [65]:
game_df["GAME_DATE"] = game_df["GAME_DATE_away"]
game_df["MATCHUP"] = game_df["MATCHUP_away"]
game_df["SEASON_ID"] = game_df["SEASON_ID_away"]
game_df["SEASON"] = game_df["SEASON_away"]
game_df.drop(columns=["is_home_home", "SEASON_ID_away", "SEASON_ID_home", "GAME_DATE_away", 
                      "GAME_DATE_home", "is_home_away", "SEASON_away", "SEASON_home", "MATCHUP_away", 
                      "MATCHUP_home", "VIDEO_AVAILABLE_away", "VIDEO_AVAILABLE_home"], inplace=True)

In [66]:
game_df.head()

,GAME_ID,TEAM_ID_home,TEAM_ABBREVIATION_home,TEAM_NAME_home,WL_home,MIN_home,FGM_home,FGA_home,FG_PCT_home,FG3M_home,FG3A_home,FG3_PCT_home,FTM_home,FTA_home,FT_PCT_home,OREB_home,DREB_home,REB_home,AST_home,STL_home,BLK_home,TOV_home,PF_home,PTS_home,PLUS_MINUS_home,TEAM_ID_away,TEAM_ABBREVIATION_away,TEAM_NAME_away,WL_away,MIN_away,FGM_away,FGA_away,FG_PCT_away,FG3M_away,FG3A_away,FG3_PCT_away,FTM_away,FTA_away,FT_PCT_away,OREB_away,DREB_away,REB_away,AST_away,STL_away,BLK_away,TOV_away,PF_away,PTS_away,PLUS_MINUS_away,GAME_DATE,MATCHUP,SEASON_ID,SEASON
0,22200001,1610612738,BOS,Boston Celtics,W,240,46,82,0.561,12,35,0.343,22,28,0.786,6,30,36,24,8,3,11,24,126,9,1610612755,PHI,Philadelphia 76ers,L,240,40,80,0.500,13,34,0.382,24,28,0.857,4,27,31,16,8,3,14,25,117,-9,2022-10-18,PHI @ BOS,22022,2022-23
1,22200002,1610612744,GSW,Golden State Warriors,W,240,45,99,0.455,16,45,0.356,17,23,0.739,11,37,48,31,11,4,18,23,123,14,1610612747,LAL,Los Angeles Lakers,L,240,40,94,0.426,10,40,0.250,19,25,0.760,9,39,48,23,12,4,22,18,109,-14,2022-10-18,LAL @ GSW,22022,2022-23
2,22200003,1610612765,DET,Detroit Pistons,W,240,40,94,0.426,14,38,0.368,19,24,0.792,12,29,41,31,11,4,13,21,113,4,1610612753,ORL,Orlando Magic,L,240,42,86,0.488,11,30,0.367,14,19,0.737,10,38,48,21,5,5,18,24,109,-4,2022-10-19,ORL @ DET,22022,2022-23
3,22200004,1610612754,IND,Indiana Pacers,L,240,39,97,0.402,15,42,0.357,14,21,0.667,12,30,42,21,7,5,15,20,107,-7,1610612764,WAS,Washington Wizards,W,240,42,92,0.457,11,31,0.355,19,24,0.792,14,39,53,21,5,10,17,19,114,7,2022-10-19,WAS @ IND,22022,2022-23
4,22200005,1610612737,ATL,Atlanta Hawks,W,240,45,90,0.500,7,25,0.280,20,24,0.833,4,34,38,30,12,5,9,18,117,10,1610612745,HOU,Houston Rockets,L,240,42,98,0.429,9,35,0.257,14,15,0.933,15,39,54,25,4,3,16,20,107,-10,2022-10-19,HOU @ ATL,22022,2022-23