In [4]:
import pandas as pd

In [5]:
games = pd.read_csv("../Data/processed/nba_games_clean.csv")

In [6]:
games.head()

,game_id,game_date,season,season_id,home_team_id,home_team,home_team_name,away_team_id,away_team,away_team_name,...,DREB_away,REB_away,AST_away,STL_away,BLK_away,TOV_away,PF_away,PTS_away,PLUS_MINUS_away,VIDEO_AVAILABLE_away
0,22200001,2022-10-18,2022-23,22022,1610612738,BOS,Boston Celtics,1610612755,PHI,Philadelphia 76ers,...,27,31,16,8,3,14,25,117,-9,1
1,22200002,2022-10-18,2022-23,22022,1610612744,GSW,Golden State Warriors,1610612747,LAL,Los Angeles Lakers,...,39,48,23,12,4,22,18,109,-14,1
2,22200003,2022-10-19,2022-23,22022,1610612765,DET,Detroit Pistons,1610612753,ORL,Orlando Magic,...,38,48,21,5,5,18,24,109,-4,1
3,22200004,2022-10-19,2022-23,22022,1610612754,IND,Indiana Pacers,1610612764,WAS,Washington Wizards,...,39,53,21,5,10,17,19,114,7,1
4,22200005,2022-10-19,2022-23,22022,1610612737,ATL,Atlanta Hawks,1610612745,HOU,Houston Rockets,...,39,54,25,4,3,16,20,107,-10,1

In [7]:
display(include=all)

In [8]:
games.head()

,game_id,game_date,season,season_id,home_team_id,home_team,home_team_name,away_team_id,away_team,away_team_name,...,DREB_away,REB_away,AST_away,STL_away,BLK_away,TOV_away,PF_away,PTS_away,PLUS_MINUS_away,VIDEO_AVAILABLE_away
0,22200001,2022-10-18,2022-23,22022,1610612738,BOS,Boston Celtics,1610612755,PHI,Philadelphia 76ers,...,27,31,16,8,3,14,25,117,-9,1
1,22200002,2022-10-18,2022-23,22022,1610612744,GSW,Golden State Warriors,1610612747,LAL,Los Angeles Lakers,...,39,48,23,12,4,22,18,109,-14,1
2,22200003,2022-10-19,2022-23,22022,1610612765,DET,Detroit Pistons,1610612753,ORL,Orlando Magic,...,38,48,21,5,5,18,24,109,-4,1
3,22200004,2022-10-19,2022-23,22022,1610612754,IND,Indiana Pacers,1610612764,WAS,Washington Wizards,...,39,53,21,5,10,17,19,114,7,1
4,22200005,2022-10-19,2022-23,22022,1610612737,ATL,Atlanta Hawks,1610612745,HOU,Houston Rockets,...,39,54,25,4,3,16,20,107,-10,1

In [9]:
pd.set_option('display.max_columns', None)
games.head()

,game_id,game_date,season,season_id,home_team_id,home_team,home_team_name,away_team_id,away_team,away_team_name,home_win,WL_home,MIN_home,FGM_home,FGA_home,FG_PCT_home,FG3M_home,FG3A_home,FG3_PCT_home,FTM_home,FTA_home,FT_PCT_home,OREB_home,DREB_home,REB_home,AST_home,STL_home,BLK_home,TOV_home,PF_home,PTS_home,PLUS_MINUS_home,VIDEO_AVAILABLE_home,WL_away,MIN_away,FGM_away,FGA_away,FG_PCT_away,FG3M_away,FG3A_away,FG3_PCT_away,FTM_away,FTA_away,FT_PCT_away,OREB_away,DREB_away,REB_away,AST_away,STL_away,BLK_away,TOV_away,PF_away,PTS_away,PLUS_MINUS_away,VIDEO_AVAILABLE_away
0,22200001,2022-10-18,2022-23,22022,1610612738,BOS,Boston Celtics,1610612755,PHI,Philadelphia 76ers,1,W,240,46,82,0.561,12,35,0.343,22,28,0.786,6,30,36,24,8,3,11,24,126,9,1,L,240,40,80,0.500,13,34,0.382,24,28,0.857,4,27,31,16,8,3,14,25,117,-9,1
1,22200002,2022-10-18,2022-23,22022,1610612744,GSW,Golden State Warriors,1610612747,LAL,Los Angeles Lakers,1,W,240,45,99,0.455,16,45,0.356,17,23,0.739,11,37,48,31,11,4,18,23,123,14,1,L,240,40,94,0.426,10,40,0.250,19,25,0.760,9,39,48,23,12,4,22,18,109,-14,1
2,22200003,2022-10-19,2022-23,22022,1610612765,DET,Detroit Pistons,1610612753,ORL,Orlando Magic,1,W,240,40,94,0.426,14,38,0.368,19,24,0.792,12,29,41,31,11,4,13,21,113,4,1,L,240,42,86,0.488,11,30,0.367,14,19,0.737,10,38,48,21,5,5,18,24,109,-4,1
3,22200004,2022-10-19,2022-23,22022,1610612754,IND,Indiana Pacers,1610612764,WAS,Washington Wizards,0,L,240,39,97,0.402,15,42,0.357,14,21,0.667,12,30,42,21,7,5,15,20,107,-7,1,W,240,42,92,0.457,11,31,0.355,19,24,0.792,14,39,53,21,5,10,17,19,114,7,1
4,22200005,2022-10-19,2022-23,22022,1610612737,ATL,Atlanta Hawks,1610612745,HOU,Houston Rockets,1,W,240,45,90,0.500,7,25,0.280,20,24,0.833,4,34,38,30,12,5,9,18,117,10,1,L,240,42,98,0.429,9,35,0.257,14,15,0.933,15,39,54,25,4,3,16,20,107,-10,1

In [13]:
games.home_team.value_counts()

home_team
LAL    165
MIL    165
SAC    164
OKC    164
CLE    164
DEN    164
CHI    164
POR    164
HOU    164
CHA    164
GSW    164
PHI    164
BOS    164
PHX    164
TOR    164
BKN    164
MIA    164
UTA    164
LAC    164
MIN    164
MEM    163
NYK    163
WAS    163
DAL    163
ATL    163
IND    163
NOP    163
ORL    163
SAS    162
DET    162
Name: count, dtype: int64

In [12]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4910 entries, 0 to 4909
Data columns (total 55 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   game_id               4910 non-null   int64
 1   game_date             4910 non-null   object
 2   season                4910 non-null   object
 3   season_id             4910 non-null   int64
 4   home_team_id          4910 non-null   int64
 5   home_team             4910 non-null   object
 6   home_team_name        4910 non-null   object
 7   away_team_id          4910 non-null   int64
 8   away_team             4910 non-null   object
 9   away_team_name        4910 non-null   object
 10  home_win              4910 non-null   int64
 11  WL_home               4910 non-null   object
 12  MIN_home              4910 non-null   int64
 13  FGM_home              4910 non-null   int64
 14  FGA_home              4910 non-null   int64
 15  FG_PCT_home           4910 non-null   float64
 16  FG3M_home             4910 non-null   int64
 17  FG3A_home             4910 non-null   int64
 18  FG3_PCT_home          4910 non-null   float64
 19  FTM_home              4910 non-null   int64
 20  FTA_home              4910 non-null   int64
 21  FT_PCT_home           4910 non-null   float64
 22  OREB_home             4910 non-null   int64
 23  DREB_home             4910 non-null   int64
 24  REB_home              4910 non-null   int64
 25  AST_home              4910 non-null   int64
 26  STL_home              4910 non-null   int64
 27  BLK_home              4910 non-null   int64
 28  TOV_home              4910 non-null   int64
 29  PF_home               4910 non-null   int64
 30  PTS_home              4910 non-null   int64
 31  PLUS_MINUS_home       4910 non-null   int64
 32  VIDEO_AVAILABLE_home  4910 non-null   int64
 33  WL_away               4910 non-null   object
 34  MIN_away              4910 non-null   int64
 35  FGM_away              4910 non-null   int64
 36  FGA_away              4910 non-null   int64
 37  FG_PCT_away           4910 non-null   float64
 38  FG3M_away             4910 non-null   int64
 39  FG3A_away             4910 non-null   int64
 40  FG3_PCT_away          4910 non-null   float64
 41  FTM_away              4910 non-null   int64
 42  FTA_away              4910 non-null   int64
 43  FT_PCT_away           4910 non-null   float64
 44  OREB_away             4910 non-null   int64
 45  DREB_away             4910 non-null   int64
 46  REB_away              4910 non-null   int64
 47  AST_away              4910 non-null   int64
 48  STL_away              4910 non-null   int64
 49  BLK_away              4910 non-null   int64
 50  TOV_away              4910 non-null   int64
 51  PF_away               4910 non-null   int64
 52  PTS_away              4910 non-null   int64
 53  PLUS_MINUS_away       4910 non-null   int64
 54  VIDEO_AVAILABLE_away  4910 non-null   int64
dtypes: float64(6), int64(41), object(8)
memory usage: 2.1+ MB

In [15]:
games["WL_home"] = games.apply(lambda x: 1 if x["WL_home"] == "W" else 0, axis=1)
games["WL_away"] = games.apply(lambda x: 1 if x["WL_away"] == "W" else 0, axis=1)

In [16]:
games

,game_id,game_date,season,season_id,home_team_id,home_team,home_team_name,away_team_id,away_team,away_team_name,home_win,WL_home,MIN_home,FGM_home,FGA_home,FG_PCT_home,FG3M_home,FG3A_home,FG3_PCT_home,FTM_home,FTA_home,FT_PCT_home,OREB_home,DREB_home,REB_home,AST_home,STL_home,BLK_home,TOV_home,PF_home,PTS_home,PLUS_MINUS_home,VIDEO_AVAILABLE_home,WL_away,MIN_away,FGM_away,FGA_away,FG_PCT_away,FG3M_away,FG3A_away,FG3_PCT_away,FTM_away,FTA_away,FT_PCT_away,OREB_away,DREB_away,REB_away,AST_away,STL_away,BLK_away,TOV_away,PF_away,PTS_away,PLUS_MINUS_away,VIDEO_AVAILABLE_away
0,22200001,2022-10-18,2022-23,22022,1610612738,BOS,Boston Celtics,1610612755,PHI,Philadelphia 76ers,1,1,240,46,82,0.561,12,35,0.343,22,28,0.786,6,30,36,24,8,3,11,24,126,9,1,0,240,40,80,0.500,13,34,0.382,24,28,0.857,4,27,31,16,8,3,14,25,117,-9,1
1,22200002,2022-10-18,2022-23,22022,1610612744,GSW,Golden State Warriors,1610612747,LAL,Los Angeles Lakers,1,1,240,45,99,0.455,16,45,0.356,17,23,0.739,11,37,48,31,11,4,18,23,123,14,1,0,240,40,94,0.426,10,40,0.250,19,25,0.760,9,39,48,23,12,4,22,18,109,-14,1
2,22200003,2022-10-19,2022-23,22022,1610612765,DET,Detroit Pistons,1610612753,ORL,Orlando Magic,1,1,240,40,94,0.426,14,38,0.368,19,24,0.792,12,29,41,31,11,4,13,21,113,4,1,0,240,42,86,0.488,11,30,0.367,14,19,0.737,10,38,48,21,5,5,18,24,109,-4,1
3,22200004,2022-10-19,2022-23,22022,1610612754,IND,Indiana Pacers,1610612764,WAS,Washington Wizards,0,0,240,39,97,0.402,15,42,0.357,14,21,0.667,12,30,42,21,7,5,15,20,107,-7,1,1,240,42,92,0.457,11,31,0.355,19,24,0.792,14,39,53,21,5,10,17,19,114,7,1
4,22200005,2022-10-19,2022-23,22022,1610612737,ATL,Atlanta Hawks,1610612745,HOU,Houston Rockets,1,1,240,45,90,0.500,7,25,0.280,20,24,0.833,4,34,38,30,12,5,9,18,117,10,1,0,240,42,98,0.429,9,35,0.257,14,15,0.933,15,39,54,25,4,3,16,20,107,-10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4905,22501196,2026-04-12,2025-26,22025,1610612760,OKC,Oklahoma City Thunder,1610612756,PHX,Phoenix Suns,0,0,240,41,95,0.432,18,46,0.391,3,9,0.333,9,27,36,32,9,7,10,8,103,-32,1,1,240,56,101,0.554,20,41,0.488,3,6,0.500,13,41,54,28,5,8,13,9,135,32,1
4906,22501197,2026-04-12,2025-26,22025,1610612759,SAS,San Antonio Spurs,1610612743,DEN,Denver Nuggets,0,0,240,45,99,0.455,15,47,0.319,13,18,0.722,14,31,45,27,5,5,9,18,118,-10,1,1,240,50,100,0.500,11,30,0.367,17,22,0.773,19,39,58,30,4,5,12,16,128,10,1
4907,22501198,2026-04-12,2025-26,22025,1610612747,LAL,Los Angeles Lakers,1610612762,UTA,Utah Jazz,1,1,240,51,93,0.548,15,34,0.441,14,17,0.824,11,38,49,37,12,6,17,20,131,24,1,0,240,41,94,0.436,7,34,0.206,18,27,0.667,17,25,42,25,13,4,16,14,107,-24,1
4908,22501199,2026-04-12,2025-26,22025,1610612746,LAC,LA Clippers,1610612744,GSW,Golden State Warriors,1,1,240,42,89,0.472,14,39,0.359,17,19,0.895,10,34,44,27,3,4,10,24,115,5,1,0,240,36,86,0.419,11,39,0.282,27,32,0.844,16,31,47,24,3,3,10,21,110,-5,1
4909,22501200,2026-04-12,2025-26,22025,1610612757,POR,Portland Trail Blazers,1610612758,SAC,Sacramento Kings,1,1,240,47,101,0.465,16,46,0.348,12,15,0.800,18,28,46,28,9,3,12,21,122,12,1,0,240,40,83,0.482,7,21,0.333,23,31,0.742,15,32,47,24,7,8,17,18,110,-12,1

In [17]:
games["game_date"] = pd.to_datetime(games["game_date"])

In [18]:
home = games[[
    "game_id", "game_date", "season",
    "home_team", "away_team",
    "home_win", "PTS_home", "PTS_away", "PLUS_MINUS_home"
]].copy()

home = home.rename(columns={
    "home_team": "team",
    "away_team": "opponent",
    "PTS_home": "points_for",
    "PTS_away": "points_against",
    "PLUS_MINUS_home": "point_diff",
})

home["is_home"] = 1
home["win"] = home["home_win"]

away = games[[
    "game_id", "game_date", "season",
    "away_team", "home_team",
    "home_win", "PTS_away", "PTS_home", "PLUS_MINUS_away"
]].copy()

away = away.rename(columns={
    "away_team": "team",
    "home_team": "opponent",
    "PTS_away": "points_for",
    "PTS_home": "points_against",
    "PLUS_MINUS_away": "point_diff",
})

away["is_home"] = 0
away["win"] = 1 - away["home_win"]

team_games = pd.concat([home, away], ignore_index=True)
team_games = team_games.sort_values(["team", "game_date", "game_id"])

In [19]:
team_games.head()

,game_id,game_date,season,team,opponent,home_win,points_for,points_against,point_diff,is_home,win
4,22200005,2022-10-19,2022-23,ATL,HOU,1,117,107,10,1,1
19,22200020,2022-10-21,2022-23,ATL,ORL,1,108,98,10,1,1
37,22200038,2022-10-23,2022-23,ATL,CHA,0,109,126,-17,1,0
4966,22200057,2022-10-26,2022-23,ATL,DET,0,118,113,5,0,1
4979,22200070,2022-10-28,2022-23,ATL,DET,0,136,112,24,0,1

In [20]:
team_games

,game_id,game_date,season,team,opponent,home_win,points_for,points_against,point_diff,is_home,win
4,22200005,2022-10-19,2022-23,ATL,HOU,1,117,107,10,1,1
19,22200020,2022-10-21,2022-23,ATL,ORL,1,108,98,10,1,1
37,22200038,2022-10-23,2022-23,ATL,CHA,0,109,126,-17,1,0
4966,22200057,2022-10-26,2022-23,ATL,DET,0,118,113,5,0,1
4979,22200070,2022-10-28,2022-23,ATL,DET,0,136,112,24,0,1
...,...,...,...,...,...,...,...,...,...,...,...
9752,22501133,2026-04-05,2025-26,WAS,BKN,1,115,121,-6,0,0
4857,22501148,2026-04-07,2025-26,WAS,CHI,0,98,129,-31,1,0
4875,22501166,2026-04-09,2025-26,WAS,CHI,0,108,119,-11,1,0
4881,22501172,2026-04-10,2025-26,WAS,MIA,0,117,140,-23,1,0
9806,22501187,2026-04-12,2025-26,WAS,CLE,1,117,130,-13,0,0

In [21]:
team_games["games_played_before"] = team_games.groupby(["season", "team"]).cumcount()

team_games["season_wins_before"] = (
    team_games.groupby(["season", "team"])["win"]
    .cumsum()
    .shift(1)
)

team_games["season_win_pct_before"] = (
    team_games["season_wins_before"] / team_games["games_played_before"]
)

In [22]:
team_games.head()

,game_id,game_date,season,team,opponent,home_win,points_for,points_against,point_diff,is_home,win,games_played_before,season_wins_before,season_win_pct_before
4,22200005,2022-10-19,2022-23,ATL,HOU,1,117,107,10,1,1,0,NaN,NaN
19,22200020,2022-10-21,2022-23,ATL,ORL,1,108,98,10,1,1,1,1.0,1.000000
37,22200038,2022-10-23,2022-23,ATL,CHA,0,109,126,-17,1,0,2,2.0,1.000000
4966,22200057,2022-10-26,2022-23,ATL,DET,0,118,113,5,0,1,3,2.0,0.666667
4979,22200070,2022-10-28,2022-23,ATL,DET,0,136,112,24,0,1,4,3.0,0.750000

In [23]:
team_games["last5_win_pct"] = (
    team_games.groupby(["season", "team"])["win"]
    .transform(lambda s: s.shift(1).rolling(5, min_periods=1).mean())
)

team_games["last5_point_diff"] = (
    team_games.groupby(["season", "team"])["point_diff"]
    .transform(lambda s: s.shift(1).rolling(5, min_periods=1).mean())
)

In [24]:
team_games.head()

,game_id,game_date,season,team,opponent,home_win,points_for,points_against,point_diff,is_home,win,games_played_before,season_wins_before,season_win_pct_before,last5_win_pct,last5_point_diff
4,22200005,2022-10-19,2022-23,ATL,HOU,1,117,107,10,1,1,0,NaN,NaN,NaN,NaN
19,22200020,2022-10-21,2022-23,ATL,ORL,1,108,98,10,1,1,1,1.0,1.000000,1.000000,10.0
37,22200038,2022-10-23,2022-23,ATL,CHA,0,109,126,-17,1,0,2,2.0,1.000000,1.000000,10.0
4966,22200057,2022-10-26,2022-23,ATL,DET,0,118,113,5,0,1,3,2.0,0.666667,0.666667,1.0
4979,22200070,2022-10-28,2022-23,ATL,DET,0,136,112,24,0,1,4,3.0,0.750000,0.750000,2.0

In [25]:
team_games["last5_win_pct"] = (
    team_games.groupby(["season", "team"])["win"]
    .transform(lambda s: s.shift(1).rolling(5, min_periods=1).mean())
)

team_games["last5_point_diff"] = (
    team_games.groupby(["season", "team"])["point_diff"]
    .transform(lambda s: s.shift(1).rolling(5, min_periods=1).mean())
)

team_games["rest_days"] = (
    team_games.groupby("team")["game_date"]
    .diff()
    .dt.days
)

In [26]:
team_games.head()

,game_id,game_date,season,team,opponent,home_win,points_for,points_against,point_diff,is_home,win,games_played_before,season_wins_before,season_win_pct_before,last5_win_pct,last5_point_diff,rest_days
4,22200005,2022-10-19,2022-23,ATL,HOU,1,117,107,10,1,1,0,NaN,NaN,NaN,NaN,NaN
19,22200020,2022-10-21,2022-23,ATL,ORL,1,108,98,10,1,1,1,1.0,1.000000,1.000000,10.0,2.0
37,22200038,2022-10-23,2022-23,ATL,CHA,0,109,126,-17,1,0,2,2.0,1.000000,1.000000,10.0,2.0
4966,22200057,2022-10-26,2022-23,ATL,DET,0,118,113,5,0,1,3,2.0,0.666667,0.666667,1.0,3.0
4979,22200070,2022-10-28,2022-23,ATL,DET,0,136,112,24,0,1,4,3.0,0.750000,0.750000,2.0,2.0

In [27]:
feature_cols = [
    "game_id",
    "team",
    "season_win_pct_before",
    "last5_win_pct",
    "last5_point_diff",
    "rest_days",
]

home_features = team_games[team_games["is_home"] == 1][feature_cols].copy()
away_features = team_games[team_games["is_home"] == 0][feature_cols].copy()

home_features = home_features.add_prefix("home_")
away_features = away_features.add_prefix("away_")

features = games[[
    "game_id", "game_date", "season", "home_team", "away_team", "home_win"
]].copy()

features = features.merge(
    home_features,
    left_on=["game_id", "home_team"],
    right_on=["home_game_id", "home_team"],
    how="left",
)

features = features.merge(
    away_features,
    left_on=["game_id", "away_team"],
    right_on=["away_game_id", "away_team"],
    how="left",
)

features["win_pct_diff"] = (
    features["home_season_win_pct_before"]
    - features["away_season_win_pct_before"]
)

features["last5_win_pct_diff"] = (
    features["home_last5_win_pct"]
    - features["away_last5_win_pct"]
)

features["last5_point_diff_diff"] = (
    features["home_last5_point_diff"]
    - features["away_last5_point_diff"]
)

features["rest_days_diff"] = (
    features["home_rest_days"]
    - features["away_rest_days"]
)

In [28]:
features

,game_id,game_date,season,home_team,away_team,home_win,home_game_id,home_season_win_pct_before,home_last5_win_pct,home_last5_point_diff,home_rest_days,away_game_id,away_season_win_pct_before,away_last5_win_pct,away_last5_point_diff,away_rest_days,win_pct_diff,last5_win_pct_diff,last5_point_diff_diff,rest_days_diff
0,22200001,2022-10-18,2022-23,BOS,PHI,1,22200001,inf,NaN,NaN,NaN,22200001,inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22200002,2022-10-18,2022-23,GSW,LAL,1,22200002,inf,NaN,NaN,NaN,22200002,inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22200003,2022-10-19,2022-23,DET,ORL,1,22200003,inf,NaN,NaN,NaN,22200003,inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,22200004,2022-10-19,2022-23,IND,WAS,0,22200004,inf,NaN,NaN,NaN,22200004,inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22200005,2022-10-19,2022-23,ATL,HOU,1,22200005,NaN,NaN,NaN,NaN,22200005,inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4905,22501196,2026-04-12,2025-26,OKC,PHX,0,22501196,0.800000,0.8,22.4,2.0,22501196,0.543210,0.4,-9.4,2.0,0.256790,0.4,31.8,0.0
4906,22501197,2026-04-12,2025-26,SAS,DEN,0,22501197,0.762500,0.8,12.0,2.0,22501197,0.654321,1.0,11.4,2.0,0.108179,-0.2,0.6,0.0
4907,22501198,2026-04-12,2025-26,LAL,UTA,1,22501198,0.641975,0.4,-8.2,2.0,22501198,0.271605,0.2,-11.0,2.0,0.370370,0.2,2.8,0.0
4908,22501199,2026-04-12,2025-26,LAC,GSW,1,22501199,0.506173,0.4,-2.8,2.0,22501199,0.456790,0.2,-5.0,2.0,0.049383,0.2,2.2,0.0
4909,22501200,2026-04-12,2025-26,POR,SAC,1,22501200,0.506173,0.6,5.0,2.0,22501200,0.271605,0.6,-3.2,2.0,0.234568,0.0,8.2,0.0